# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacto', '0002_auto_20180613_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
